# Generated by Django 3.2.1 on 2021-05-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='iamge',
            new_name='image',
        ),
    ]
